In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

from datetime import datetime

In [2]:
pwd

'H:\\python\\tsa\\UDEMY_TSA_FINAL\\01-NumPy'

# Array
## Creating array

## Creating array from list

In [3]:
my_list = [1,2,3]

In [4]:
type(my_list)

list

In [5]:
my_arr = np.array(my_list)

In [6]:
my_arr

array([1, 2, 3])

In [7]:
type(my_arr)

numpy.ndarray

In [8]:
my_nestes_list = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat = np.array(my_nestes_list)

In [10]:
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
my_mat.shape

(3, 3)

## Creating array from numpy build-in functions

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((4,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [19]:
np.linspace(start=0,stop=10,num=3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(start=0,stop=10,num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
len(np.linspace(start=0,stop=10,num=20))

20

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Creating array of random numbers

In [23]:
np.random.rand(1)

array([0.65907146])

In [24]:
np.random.rand(4)

array([0.35752885, 0.26375633, 0.40527581, 0.01078646])

In [25]:
np.random.rand(4,3)

array([[0.87710369, 0.94744708, 0.70211027],
       [0.08802744, 0.78003983, 0.71930998],
       [0.27023874, 0.81626695, 0.57213701],
       [0.61522254, 0.38289264, 0.2185864 ]])

In [26]:
np.random.randn(1)

array([-1.82623156])

In [27]:
np.random.randn(10)

array([ 1.10243348, -1.20206503, -0.16271711,  0.9242497 ,  0.15620827,
        1.76015748,  0.87332616, -0.62933063,  0.48128083, -0.58172234])

In [28]:
np.random.normal(loc=1,scale=10)

7.299293560330039

In [29]:
np.random.randint(1,100,10)

array([16, 71, 22, 61, 88, 30, 70, 93, 67, 97])

In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

## Array attributes and methods

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ran_arr = np.random.randint(0,50,10)

In [35]:
ran_arr

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.max()

24

In [38]:
arr.argmax()

24

In [39]:
arr.min()

0

In [40]:
arr.argmin()

0

In [41]:
print(ran_arr.max(), ran_arr.argmax())

47 0


In [42]:
ran_arr.dtype

dtype('int32')

### Indexing and Selection

In [43]:
arr1 = np.arange(0,11)

In [44]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr1[8]

8

In [46]:
arr1[1:5]

array([1, 2, 3, 4])

In [47]:
arr[:5]

array([0, 1, 2, 3, 4])

In [48]:
arr1[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr1[-1]

10

In [50]:
arr1+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [51]:
arr1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [52]:
arr1 ** 2 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [53]:
slice_arr1 = arr1[:6]
slice_arr1[:] = 99

In [54]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr1 = np.arange(0,11)

In [56]:
arr1_copy = arr1.copy()

In [57]:
arr1_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr1_copy[:] = 99

In [59]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr1_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [61]:
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
my_mat[1,-1]

6

In [63]:
my_mat[1:2,2:]

array([[6]])

## Conditional Selection

In [64]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr1[arr1 > 4]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
my_mat[my_mat>5]

array([6, 7, 8, 9])

In [67]:
my_mat[my_mat == 5]

array([5])

## NumPy operations

In [68]:
arr1 + arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
arr1 / arr1

C:\Users\HP\anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [70]:
1 / arr1

C:\Users\HP\anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [71]:
0 / arr1

C:\Users\HP\anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

## Array functions

In [72]:
np.sqrt(my_mat)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [73]:
np.log(arr1)

C:\Users\HP\anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [74]:
np.sum(arr1)

55

In [75]:
my_mat.sum()

45

In [76]:
my_mat.sum(axis=0)

array([12, 15, 18])

In [77]:
my_mat.sum(axis=1)

array([ 6, 15, 24])